### ISSUE TITLE
Json resume

### ISSUE THREAD

**Issue by pmiossec** [dcyou/resume#41]
Some serendipity makes me discover your project.

JFYI, do you know that there is  open source initiative to create a JSON-based standard for resumes?
https://jsonresume.org/

That's not a feature request, but I would like to inform you. Perhaps you could find it interesting to support it...

**Comment by dcyou** [comment]
Thanks and sorry for the delay I completely missed to answer... Yeah I know but as I said it was for me a way to tame Nuxt and ElementUI :)
